// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/backup.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{0}
}

type BackupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*Backup              `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupListResponse) Reset() {
	*x = BackupListResponse{}
	mi := &file_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupListResponse) ProtoMessage() {}

func (x *BackupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupListResponse.ProtoReflect.Descriptor instead.
func (*BackupListResponse) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *BackupListResponse) GetBackups() []*Backup {
	if x != nil {
		return x.Backups
	}
	return nil
}

type Backup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *Backup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backup) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Backup) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RestoreBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreBackupRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RestoreBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{4}
}

type GetBackupByVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupByVersionRequest) Reset() {
	*x = GetBackupByVersionRequest{}
	mi := &file_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupByVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupByVersionRequest) ProtoMessage() {}

func (x *GetBackupByVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupByVersionRequest.ProtoReflect.Descriptor instead.
func (*GetBackupByVersionRequest) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *GetBackupByVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetBackupByVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backup        *Backup                `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupByVersionResponse) Reset() {
	*x = GetBackupByVersionResponse{}
	mi := &file_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupByVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupByVersionResponse) ProtoMessage() {}

func (x *GetBackupByVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupByVersionResponse.ProtoReflect.Descriptor instead.
func (*GetBackupByVersionResponse) Descriptor() ([]byte, []int) {
	return file_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *GetBackupByVersionResponse) GetBackup() *Backup {
	if x != nil {
		return x.Backup
	}
	return nil
}

var File_v1_backup_proto protoreflect.FileDescriptor

const file_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/backup.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12ListBackupsRequest\":\n" +
	"\x12BackupListResponse\x12$\n" +
	"\abackups\x18\x01 \x03(\v2\n" +
	".v1.BackupR\abackups\"p\n" +
	"\x06Backup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"0\n" +
	"\x14RestoreBackupRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x17\n" +
	"\x15RestoreBackupResponse\"5\n" +
	"\x19GetBackupByVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"@\n" +
	"\x1aGetBackupByVersionResponse\x12\"\n" +
	"\x06backup\x18\x01 \x01(\v2\n" +
	".v1.BackupR\x06backup2\xe9\x01\n" +
	"\rBackupService\x12=\n" +
	"\vListBackups\x12\x16.v1.ListBackupsRequest\x1a\x16.v1.BackupListResponse\x12D\n" +
	"\rRestoreBackup\x12\x18.v1.RestoreBackupRequest\x1a\x19.v1.RestoreBackupResponse\x12S\n" +
	"\x12GetBackupByVersion\x12\x1d.v1.GetBackupByVersionRequest\x1a\x1e.v1.GetBackupByVersionResponseBg\n" +
	"\x06com.v1B\vBackupProtoP\x01Z(github.com/metal-stack/droptailer/api/v1\xa2\x02\x03VXX\xaa\x02\x02V1\xca\x02\x02V1\xe2\x02\x0eV1\\GPBMetadata\xea\x02\x02V1b\x06proto3"

var (
	file_v1_backup_proto_rawDescOnce sync.Once
	file_v1_backup_proto_rawDescData []byte
)

func file_v1_backup_proto_rawDescGZIP() []byte {
	file_v1_backup_proto_rawDescOnce.Do(func() {
		file_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_backup_proto_rawDesc), len(file_v1_backup_proto_rawDesc)))
	})
	return file_v1_backup_proto_rawDescData
}

var file_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_backup_proto_goTypes = []any{
	(*ListBackupsRequest)(nil),         // 0: v1.ListBackupsRequest
	(*BackupListResponse)(nil),         // 1: v1.BackupListResponse
	(*Backup)(nil),                     // 2: v1.Backup
	(*RestoreBackupRequest)(nil),       // 3: v1.RestoreBackupRequest
	(*RestoreBackupResponse)(nil),      // 4: v1.RestoreBackupResponse
	(*GetBackupByVersionRequest)(nil),  // 5: v1.GetBackupByVersionRequest
	(*GetBackupByVersionResponse)(nil), // 6: v1.GetBackupByVersionResponse
	(*timestamppb.Timestamp)(nil),      // 7: google.protobuf.Timestamp
}
var file_v1_backup_proto_depIdxs = []int32{
	2, // 0: v1.BackupListResponse.backups:type_name -> v1.Backup
	7, // 1: v1.Backup.timestamp:type_name -> google.protobuf.Timestamp
	2, // 2: v1.GetBackupByVersionResponse.backup:type_name -> v1.Backup
	0, // 3: v1.BackupService.ListBackups:input_type -> v1.ListBackupsRequest
	3, // 4: v1.BackupService.RestoreBackup:input_type -> v1.RestoreBackupRequest
	5, // 5: v1.BackupService.GetBackupByVersion:input_type -> v1.GetBackupByVersionRequest
	1, // 6: v1.BackupService.ListBackups:output_type -> v1.BackupListResponse
	4, // 7: v1.BackupService.RestoreBackup:output_type -> v1.RestoreBackupResponse
	6, // 8: v1.BackupService.GetBackupByVersion:output_type -> v1.GetBackupByVersionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_backup_proto_init() }
func file_v1_backup_proto_init() {
	if File_v1_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_backup_proto_rawDesc), len(file_v1_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_backup_proto_goTypes,
		DependencyIndexes: file_v1_backup_proto_depIdxs,
		MessageInfos:      file_v1_backup_proto_msgTypes,
	}.Build()
	File_v1_backup_proto = out.File
	file_v1_backup_proto_goTypes = nil
	file_v1_backup_proto_depIdxs = nil
}
