// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/database.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_v1_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_v1_database_proto_rawDescGZIP(), []int{0}
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_v1_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_v1_database_proto_rawDescGZIP(), []int{1}
}

var File_v1_database_proto protoreflect.FileDescriptor

const file_v1_database_proto_rawDesc = "" +
	"\n" +
	"\x11v1/database.proto\x12\x02v1\"\x15\n" +
	"\x13CreateBackupRequest\"\x16\n" +
	"\x14CreateBackupResponse2T\n" +
	"\x0fDatabaseService\x12A\n" +
	"\fCreateBackup\x12\x17.v1.CreateBackupRequest\x1a\x18.v1.CreateBackupResponseBi\n" +
	"\x06com.v1B\rDatabaseProtoP\x01Z(github.com/metal-stack/droptailer/api/v1\xa2\x02\x03VXX\xaa\x02\x02V1\xca\x02\x02V1\xe2\x02\x0eV1\\GPBMetadata\xea\x02\x02V1b\x06proto3"

var (
	file_v1_database_proto_rawDescOnce sync.Once
	file_v1_database_proto_rawDescData []byte
)

func file_v1_database_proto_rawDescGZIP() []byte {
	file_v1_database_proto_rawDescOnce.Do(func() {
		file_v1_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_database_proto_rawDesc), len(file_v1_database_proto_rawDesc)))
	})
	return file_v1_database_proto_rawDescData
}

var file_v1_database_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_database_proto_goTypes = []any{
	(*CreateBackupRequest)(nil),  // 0: v1.CreateBackupRequest
	(*CreateBackupResponse)(nil), // 1: v1.CreateBackupResponse
}
var file_v1_database_proto_depIdxs = []int32{
	0, // 0: v1.DatabaseService.CreateBackup:input_type -> v1.CreateBackupRequest
	1, // 1: v1.DatabaseService.CreateBackup:output_type -> v1.CreateBackupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_database_proto_init() }
func file_v1_database_proto_init() {
	if File_v1_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_database_proto_rawDesc), len(file_v1_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_database_proto_goTypes,
		DependencyIndexes: file_v1_database_proto_depIdxs,
		MessageInfos:      file_v1_database_proto_msgTypes,
	}.Build()
	File_v1_database_proto = out.File
	file_v1_database_proto_goTypes = nil
	file_v1_database_proto_depIdxs = nil
}
