// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/initializer.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusResponse_InitializerStatus int32

const (
	StatusResponse_CHECKING  StatusResponse_InitializerStatus = 0
	StatusResponse_RESTORING StatusResponse_InitializerStatus = 1
	StatusResponse_DONE      StatusResponse_InitializerStatus = 2
)

var StatusResponse_InitializerStatus_name = map[int32]string{
	0: "CHECKING",
	1: "RESTORING",
	2: "DONE",
}

var StatusResponse_InitializerStatus_value = map[string]int32{
	"CHECKING":  0,
	"RESTORING": 1,
	"DONE":      2,
}

func (x StatusResponse_InitializerStatus) String() string {
	return proto.EnumName(StatusResponse_InitializerStatus_name, int32(x))
}

func (StatusResponse_InitializerStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ebf8115faccd7548, []int{1, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebf8115faccd7548, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StatusResponse struct {
	Status               StatusResponse_InitializerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=v1.StatusResponse_InitializerStatus" json:"status,omitempty"`
	Message              string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebf8115faccd7548, []int{1}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetStatus() StatusResponse_InitializerStatus {
	if m != nil {
		return m.Status
	}
	return StatusResponse_CHECKING
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("v1.StatusResponse_InitializerStatus", StatusResponse_InitializerStatus_name, StatusResponse_InitializerStatus_value)
	proto.RegisterType((*Empty)(nil), "v1.Empty")
	proto.RegisterType((*StatusResponse)(nil), "v1.StatusResponse")
}

func init() { proto.RegisterFile("v1/initializer.proto", fileDescriptor_ebf8115faccd7548) }

var fileDescriptor_ebf8115faccd7548 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x33, 0xd4, 0xcf,
	0xcc, 0xcb, 0x2c, 0xc9, 0x4c, 0xcc, 0xc9, 0xac, 0x4a, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x33, 0x54, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0x5a, 0xc2,
	0xc8, 0xc5, 0x17, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x1c, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c,
	0x2a, 0x64, 0xc3, 0xc5, 0x56, 0x0c, 0x16, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x52, 0xd1,
	0x2b, 0x33, 0xd4, 0x43, 0x55, 0xa3, 0xe7, 0x89, 0x30, 0x15, 0x2a, 0x03, 0xd5, 0x23, 0x24, 0xc1,
	0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0xe3, 0x2a, 0x59, 0x71, 0x09, 0x62, 0x68, 0x13, 0xe2, 0xe1, 0xe2, 0x70, 0xf6, 0x70, 0x75, 0xf6,
	0xf6, 0xf4, 0x73, 0x17, 0x60, 0x10, 0xe2, 0xe5, 0xe2, 0x0c, 0x72, 0x0d, 0x0e, 0xf1, 0x0f, 0x02,
	0x71, 0x19, 0x85, 0x38, 0xb8, 0x58, 0x5c, 0xfc, 0xfd, 0x5c, 0x05, 0x98, 0x8c, 0x6c, 0xb9, 0x84,
	0x90, 0xf5, 0xa6, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xa9, 0x73, 0xb1, 0x41, 0x8d, 0xe1, 0x04,
	0xb9, 0x11, 0xec, 0x23, 0x29, 0x21, 0x4c, 0xe7, 0x26, 0xb1, 0x81, 0x7d, 0x6e, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xf1, 0xa4, 0x8b, 0xe6, 0x11, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InitializerServiceClient is the client API for InitializerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InitializerServiceClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type initializerServiceClient struct {
	cc *grpc.ClientConn
}

func NewInitializerServiceClient(cc *grpc.ClientConn) InitializerServiceClient {
	return &initializerServiceClient{cc}
}

func (c *initializerServiceClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/v1.InitializerService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitializerServiceServer is the server API for InitializerService service.
type InitializerServiceServer interface {
	Status(context.Context, *Empty) (*StatusResponse, error)
}

// UnimplementedInitializerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInitializerServiceServer struct {
}

func (*UnimplementedInitializerServiceServer) Status(ctx context.Context, req *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterInitializerServiceServer(s *grpc.Server, srv InitializerServiceServer) {
	s.RegisterService(&_InitializerService_serviceDesc, srv)
}

func _InitializerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitializerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InitializerService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitializerServiceServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _InitializerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.InitializerService",
	HandlerType: (*InitializerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _InitializerService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/initializer.proto",
}
