// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: v1/initializer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusResponse_InitializerStatus int32

const (
	StatusResponse_CHECKING  StatusResponse_InitializerStatus = 0
	StatusResponse_RESTORING StatusResponse_InitializerStatus = 1
	StatusResponse_DONE      StatusResponse_InitializerStatus = 2
)

// Enum value maps for StatusResponse_InitializerStatus.
var (
	StatusResponse_InitializerStatus_name = map[int32]string{
		0: "CHECKING",
		1: "RESTORING",
		2: "DONE",
	}
	StatusResponse_InitializerStatus_value = map[string]int32{
		"CHECKING":  0,
		"RESTORING": 1,
		"DONE":      2,
	}
)

func (x StatusResponse_InitializerStatus) Enum() *StatusResponse_InitializerStatus {
	p := new(StatusResponse_InitializerStatus)
	*p = x
	return p
}

func (x StatusResponse_InitializerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_InitializerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_initializer_proto_enumTypes[0].Descriptor()
}

func (StatusResponse_InitializerStatus) Type() protoreflect.EnumType {
	return &file_v1_initializer_proto_enumTypes[0]
}

func (x StatusResponse_InitializerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_InitializerStatus.Descriptor instead.
func (StatusResponse_InitializerStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_initializer_proto_rawDescGZIP(), []int{1, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_initializer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_v1_initializer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_v1_initializer_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  StatusResponse_InitializerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=v1.StatusResponse_InitializerStatus" json:"status,omitempty"`
	Message string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_initializer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_initializer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_initializer_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() StatusResponse_InitializerStatus {
	if x != nil {
		return x.Status
	}
	return StatusResponse_CHECKING
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_initializer_proto protoreflect.FileDescriptor

var file_v1_initializer_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0xa4, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3a,
	0x0a, 0x11, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x49, 0x4e, 0x47, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x53, 0x54, 0x4f, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x32, 0x3d, 0x0a, 0x12, 0x49, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x27, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_initializer_proto_rawDescOnce sync.Once
	file_v1_initializer_proto_rawDescData = file_v1_initializer_proto_rawDesc
)

func file_v1_initializer_proto_rawDescGZIP() []byte {
	file_v1_initializer_proto_rawDescOnce.Do(func() {
		file_v1_initializer_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_initializer_proto_rawDescData)
	})
	return file_v1_initializer_proto_rawDescData
}

var file_v1_initializer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_initializer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_initializer_proto_goTypes = []interface{}{
	(StatusResponse_InitializerStatus)(0), // 0: v1.StatusResponse.InitializerStatus
	(*Empty)(nil),                         // 1: v1.Empty
	(*StatusResponse)(nil),                // 2: v1.StatusResponse
}
var file_v1_initializer_proto_depIdxs = []int32{
	0, // 0: v1.StatusResponse.status:type_name -> v1.StatusResponse.InitializerStatus
	1, // 1: v1.InitializerService.Status:input_type -> v1.Empty
	2, // 2: v1.InitializerService.Status:output_type -> v1.StatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_initializer_proto_init() }
func file_v1_initializer_proto_init() {
	if File_v1_initializer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_initializer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_initializer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_initializer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_initializer_proto_goTypes,
		DependencyIndexes: file_v1_initializer_proto_depIdxs,
		EnumInfos:         file_v1_initializer_proto_enumTypes,
		MessageInfos:      file_v1_initializer_proto_msgTypes,
	}.Build()
	File_v1_initializer_proto = out.File
	file_v1_initializer_proto_rawDesc = nil
	file_v1_initializer_proto_goTypes = nil
	file_v1_initializer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InitializerServiceClient is the client API for InitializerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InitializerServiceClient interface {
	Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type initializerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInitializerServiceClient(cc grpc.ClientConnInterface) InitializerServiceClient {
	return &initializerServiceClient{cc}
}

func (c *initializerServiceClient) Status(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/v1.InitializerService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitializerServiceServer is the server API for InitializerService service.
type InitializerServiceServer interface {
	Status(context.Context, *Empty) (*StatusResponse, error)
}

// UnimplementedInitializerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInitializerServiceServer struct {
}

func (*UnimplementedInitializerServiceServer) Status(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterInitializerServiceServer(s *grpc.Server, srv InitializerServiceServer) {
	s.RegisterService(&_InitializerService_serviceDesc, srv)
}

func _InitializerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitializerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.InitializerService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitializerServiceServer).Status(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _InitializerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.InitializerService",
	HandlerType: (*InitializerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _InitializerService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/initializer.proto",
}
