name: Build latest image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.x'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: -p bugs -p unused --timeout=3m

    - name: Build the Docker images
      run: |
        make dockerimage
        make dockerpush

    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
